from tkinter import*
def click(event):
    text=event.widget.cget("text")
    print(text)
    global scvalue
    if text=="=":
        if scvalue.get().isdigit():
            value=int(scvalue.get())
        else:
            value=eval(scvalue.get())
            
            scvalue.set(value)
            screen.update()
    elif text=="c":
        scvalue.set("")
        screen.update()
    else:
        scvalue.set(scvalue.get()+text)
        screen.update()
root=Tk()
root.geometry("500x600")
root.title("Calculator")
text_label=Label(text="Calculator-using GUI in Python",bg="black",fg="white",padx=10,pady=0,font=("sans-serif",14,"bold"),borderwidth=4,relief=SUNKEN)
text_label.pack(side="top",fill="x")
scvalue=StringVar()
scvalue.set("")
screen=Entry(root,textvar=scvalue,font="lucida 25 bold")
screen.pack(fill="x",ipadx=10,pady=10)
f=Frame(root,bg="grey")

#buttons
b=Button(f,text="c",font="lucida 25 bold",padx=20,pady=20)
b.bind("<Button-1>",click)
b.pack(side="left",padx=10,pady=5)
b=Button(f,text="=",font="lucida 25 bold",padx=20,pady=20)
b.bind("<Button-1>",click)
b.pack(side="left",padx=10,pady=5)
f.pack()
f=Frame(root,bg="grey")
b=Button(f,text="+",font="lucida 25 bold",padx=20,pady=20)
b.bind("<Button-1>",click)
b.pack(side="left",padx=10,pady=5)
b=Button(f,text="-",font="lucida 25 bold",padx=20,pady=20)
b.bind("<Button-1>",click)
b.pack(side="left",padx=10,pady=5)
b=Button(f,text="*",font="lucida 25 bold",padx=20,pady=20)
b.bind("<Button-1>",click)
b.pack(side="left",padx=10,pady=5)
b=Button(f,text="/",font="lucida 25 bold",padx=20,pady=20)
b.bind("<Button-1>",click)
b.pack(side="left",padx=10,pady=5)
b=Button(f,text="%",font="lucida 25 bold",padx=20,pady=20)
b.bind("<Button-1>",click)
b.pack(side="left",padx=10,pady=5)
f.pack()
f=Frame(root,bg="grey")
b=Button(f,text="0",font="lucida 25 bold",padx=20,pady=20)
b.bind("<Button-1>",click)
b.pack(side="left",padx=10,pady=5)
b=Button(f,text="9",font="lucida 25 bold",padx=20,pady=20)
b.bind("<Button-1>",click)
b.pack(side="left",padx=10,pady=5)
b=Button(f,text="8",font="lucida 25 bold",padx=20,pady=20)
b.bind("<Button-1>",click)
b.pack(side="left",padx=10,pady=5)
b=Button(f,text="7",font="lucida 25 bold",padx=20,pady=20)
b.bind("<Button-1>",click)
b.pack(side="left",padx=10,pady=5)
b=Button(f,text="6",font="lucida 25 bold",padx=20,pady=20)
b.bind("<Button-1>",click)
b.pack(side="left",padx=10,pady=5)
f.pack()
f=Frame(root,bg="grey")
b=Button(f,text="5",font="lucida 25 bold",padx=20,pady=20)
b.bind("<Button-1>",click)
b.pack(side="left",padx=10,pady=5)
b=Button(f,text="4",font="lucida 25 bold",padx=20,pady=20)
b.bind("<Button-1>",click)
b.pack(side="left",padx=10,pady=5)
b=Button(f,text="3",font="lucida 25 bold",padx=20,pady=20)
b.bind("<Button-1>",click)
b.pack(side="left",padx=10,pady=5)
b=Button(f,text="2",font="lucida 25 bold",padx=20,pady=20)
b.bind("<Button-1>",click)
b.pack(side="left",padx=10,pady=5)
b=Button(f,text="1",font="lucida 25 bold",padx=20,pady=20)
b.bind("<Button-1>",click)
b.pack(side="left",padx=10,pady=5)
f.pack(fill=Y)


root.mainloop()
