from tkinter import*
from tkinter import ttk
class student():
 def __init__(self,root):
        self.root=root#here self is an object of class student
        self.root.title("Student Management Sysytem")
        self.root.geometry("1500x800")

        title=Label(self.root,text="Student Management Sysytem",bd=9,relief="groove",font="cursive 20 bold",bg="black",fg="white")
        title.pack(side="top",fill=X)
    
        f=Frame(self.root,bd=5,relief=SUNKEN,bg="wheat")
        f.place(y=50,width=505,height=700)
    
        l1=Label(f,text="Student Info",bg="black",fg="white",bd=4,relief=RAISED,font="sans-serif 20 bold")
        l1.pack()
        l1.grid(row=0,columnspan=2,pady=15)
        
        name=Label(f,text="Name: ",bg="silver",fg="black",font="lucida 15 bold")
        name.grid(row=1,column=1,sticky="w")
        name_input=Entry(f,font="cursive 20")
        name_input.grid(row=1,column=2,padx=5,pady=7)

        dob=Label(f,text="DOB: ",bg="silver",fg="black",font="lucida 15 bold")
        dob.grid(row=2,column=1,sticky="w")
        dob_input=Entry(f,font="cursive 20")
        dob_input.grid(row=2,column=2,padx=5,pady=7)
       
        Roll_no=Label(f,text="Roll No: ",bg="silver",fg="black",font="lucida 15 bold")
        Roll_no.grid(row=3,column=1,sticky="w")
        Roll_no_input=Entry(f,font="cursive 20")
        Roll_no_input.grid(row=3,column=2,padx=5,pady=7)
        
        branch=Label(f,text="Branch: ",bg="silver",fg="black",font="lucida 15 bold")
        branch.grid(row=4,column=1,sticky="w")
        branch_input=Entry(f,font="cursive 20")
        branch_input.grid(row=4,column=2,padx=5,pady=7)

        contactno=Label(f,text="Contact No: ",bg="silver",fg="black",font="lucida 15 bold")
        contactno.grid(row=5,column=1,sticky="w")
        contactno_input=Entry(f,font="cursive 20")
        contactno_input.grid(row=5,column=2,padx=5,pady=7)

        email=Label(f,text="Email Id: ",bg="silver",fg="black",font="lucida 15 bold")
        email.grid(row=6,column=1,sticky="w")
        email_input=Entry(f,font="cursive 20")
        email_input.grid(row=6,column=2,padx=5,pady=7)

        gender=Label(f,text="Gender: ",bg="silver",fg="black",font="lucida 15 bold")
        gender.grid(row=7,column=1,sticky="w")
        gender=ttk.Combobox(f,font="cursive 20",state="readonly")
        gender['values']=("Male","Female","Others")
        gender.grid(row=7,column=2,pady=5,padx=5)
        
        
        btn=Frame(f,bd=3,bg="grey",relief="sunken")
        btn.place(x=20,y=500,width=340)
        addbtn=Button(btn,text="Search",width=20).grid(row=0,column=0,padx=6,pady=7)
        addbtn2=Button(btn,text="Reset",width=20).grid(row=0,column=1,padx=10,pady=7)

        d=Frame(self.root,bd=5,relief=SUNKEN,bg="silver")
        d.place(x=505,y=50,width=1000,height=700)
        search=Label(d,text="Search by",bg="black",fg="white",font="lucida 20",relief=GROOVE,width=8)
        search.grid(row=0,column=0,pady=10,padx=20,sticky="w")
        combo=ttk.Combobox(d,font="lucida",state="readonly")
        combo['values']=("Name","Roll no","Branch","CGPA","Email Id")
        combo.grid(row=0,column=1,padx=20,pady=10)

        search_input=Entry(d,font="cursive 20",width=20)
        search_input.grid(row=0,column=2,padx=5,pady=7)

        addbtn3=Button(d,text="Search",width=10).grid(row=0,column=3,padx=2,pady=10)
        # addbtn4=Button(d,text="Show All",width=10).grid(row=0,column=4,padx=2,pady=10)
        
        t=Frame(d,bd=5,relief=SUNKEN,bg="aliceblue")
        t.place(y=50,width=850,height=630)
        scrollx=Scrollbar(t,orient=HORIZONTAL)
        scrolly=Scrollbar(t,orient=VERTICAL)

        # self.table=ttk.Treeview(t,column=("name","dob","roll","branch","cgpa","email","contact"),xscrollcommand=scrollx.set,yscrollcommand=scrolly.set)
        # scrollx.pack(side=BOTTOM,fill=X)
        # scrolly.pack(side=RIGHT,fill=Y)
        # scrollx.config(command=self.table.xview)
        # scrolly.config(command=self.table.yview)

        # self.table.heading("name",text="Name")
        # self.table.heading("dob",text="DOB")
        # self.table.heading("roll",text="Roll No")
        # self.table.heading("branch",text="Branch")
        # self.table.heading("cgpa",text="CGPA")
        # self.table.heading("email",text="Email Id")
        # self.table.heading("contact",text="Contact No")

        # self.table['show']='headings'
        # self.table.column("name",width=100)
        # self.table.column("dob",width=100)
        # self.table.column("roll",width=100)
        # self.table.column("branch",width=100)
        # self.table.column("cgpa",width=100)
        # self.table.column("email",width=100)
        # self.table.column("contact",width=100)

        # self.table.pack(fill=BOTH,expand=1)

        t1=Label(t,text="Name ",bg="silver",fg="black")
        t1.grid(row=1,column=1)
        t1=Label(t,text="Roll No ",bg="silver",fg="black")
        t1.grid(row=1,column=2)
        t1=Label(t,text="Branch ",bg="silver",fg="black")
        t1.grid(row=1,column=3)
        t1=Label(t,text="CGPA ",bg="silver",fg="black")
        t1.grid(row=1,column=4)
        t1=Label(t,text="Contact No ",bg="silver",fg="black")
        t1.grid(row=1,column=5)
        t1=Label(t,text="Email Id ",bg="silver",fg="black")
        t1.grid(row=1,column=6)

        t1_input=Entry(t,font="cursive 10")
        t1_input.grid(row=2,column=1)
        t1_input=Entry(t,font="cursive 10")
        t1_input.grid(row=2,column=2)
        t1_input=Entry(t,font="cursive 10")
        t1_input.grid(row=2,column=3)
        t1_input=Entry(t,font="cursive 10")
        t1_input.grid(row=2,column=4)
        t1_input=Entry(t,font="cursive 10")
        t1_input.grid(row=2,column=5)
        t1_input=Entry(t,font="cursive 10")
        t1_input.grid(row=2,column=6)
        t1_input=Entry(t,font="cursive 10")
        t1_input.grid(row=2,column=7)

        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=3,column=1)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=3,column=2)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=3,column=3)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=3,column=4)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=3,column=5)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=3,column=6)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=3,column=7)

        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=4,column=1)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=4,column=2)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=4,column=3)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=4,column=4)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=4,column=5)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=4,column=6)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=4,column=7)

        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=5,column=1)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=5,column=2)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=5,column=3)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=5,column=4)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=5,column=5)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=5,column=6)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=5,column=7)

        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=6,column=1)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=6,column=2)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=6,column=3)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=6,column=4)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=6,column=5)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=6,column=6)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=6,column=7)

        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=7,column=1)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=7,column=2)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=7,column=3)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=7,column=4)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=7,column=5)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=7,column=6)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=7,column=7)

        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=8,column=1)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=8,column=2)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=8,column=3)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=8,column=4)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=8,column=5)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=8,column=6)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=8,column=7)

        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=9,column=1)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=9,column=2)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=9,column=3)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=9,column=4)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=9,column=5)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=9,column=6)
        t2_input=Entry(t,font="cursive 10")
        t2_input.grid(row=9,column=7)

                



        
        



class student():
    pass
    root=Tk()
    obj=student(root)

    root.mainloop() 