t1_input=Entry(t,font="cursive 20")
t1_input.grid(row=1,column=1)
t2_input=Entry(t,font="cursive 20")
t2_input.grid(row=1,column=2)
t3_input=Entry(t,font="cursive 20")
t3_input.grid(row=1,column=3)
t4_input=Entry(t,font="cursive 20")
t4_input.grid(row=1,column=4)
t5_input=Entry(t,font="cursive 20")
t5_input.grid(row=1,column=5)
t6_input=Entry(t,font="cursive 20")
t6_input.grid(row=1,column=6)
t7_input=Entry(t,font="cursive 20")
t7_input.grid(row=1,column=7)
        